import os
import django
# Set the DJANGO_SETTINGS_MODULE environment variable
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "petpal.settings")
django.setup()

from django.core.serializers import serialize
from accounts.models import PetPalUser as User
from applications.models import Application
from comments.models import Comment
from petlistings.models import PetListing
from blogposts.models import BlogPost

def create_initial_data_json():
    print("Creating initial_data.json...")
    """Create initial_data json file for testing."""
    # Users
    seeker1 = User.objects.create_user(email="bobsmith@example.com", password="123", role=User.Role.SEEKER, first_name="Bob", last_name="Smith",
                                        address="123 Main St", city='Toronto', province='ON', postal_code='10001', phone='123-456-7890')
    seeker2 = User.objects.create_user(email="kellanrodriguez@example.com", password="123", role=User.Role.SEEKER, first_name="Kellan", last_name="Rodriguez")
    seeker3 = User.objects.create_user(email="elaramonroe@example.com", password="123", role=User.Role.SEEKER, first_name="Elara", last_name="Monroe")
    seeker4 = User.objects.create_user(email="zephyrpatel@example.com", password="123", role=User.Role.SEEKER, first_name="Zephyr", last_name="Patel")
    seeker5 = User.objects.create_user(email="novasullivan@example.com", password="123", role=User.Role.SEEKER, first_name="Nova", last_name="Sullivan")

    shelter1 = User.objects.create_user(email="pethaven@example.com", password="123", first_name="Pet Haven", role=User.Role.SHELTER)
    shelter2 = User.objects.create_user(email="pawssanctuary@example.com", password="123", first_name="Paws Sanctuary", role=User.Role.SHELTER)
    shelter3 = User.objects.create_user(email="furryrefuge@example.com", password="123", first_name="Furry Refuge", role=User.Role.SHELTER)
    shelter4 = User.objects.create_user(email="cozycompanions@example.com", password="123", first_name="Cozy Companions", role=User.Role.SHELTER)
    shelter5 = User.objects.create_user(email="whiskerretreat@example.com", password="123", first_name="Whisker Retreat", role=User.Role.SHELTER)
    shelter6 = User.objects.create_user(email="tailhaven@example.com", password="123", first_name="Tail Haven", role=User.Role.SHELTER)
    shelter7 = User.objects.create_user(email="lovingpaws@example.com", password="123", first_name="Loving Paws", role=User.Role.SHELTER)
    shelter8 = User.objects.create_user(email="harmonyshelter@example.com", password="123", first_name="Harmony Shelter", role=User.Role.SHELTER)
    shelter9 = User.objects.create_user(email="happytails@example.com", password="123", first_name="Happy Tails", role=User.Role.SHELTER)
    shelter10 = User.objects.create_user(email="foreverfriends@example.com", password="123", first_name="Forever Friends", role=User.Role.SHELTER)
    
    # Petlistings
    petlisting1 = PetListing.objects.create(name="Luna", category="C", breed="Siamese", age=3, gender="F", size="S", med_history="None", behaviour="Playful", special_needs="", description="Elegant and affectionate feline.", owner=shelter1)
    petlisting2 = PetListing.objects.create(name="Max", category="D", breed="Golden Retriever", age=2, gender="M", size="L", med_history="None", behaviour="Friendly", special_needs="", description="Loyal and energetic companion.", owner=shelter2)
    petlisting3 = PetListing.objects.create(name="Whiskers", category="C", breed="Tabby", age=1, gender="X", size="M", med_history="None", behaviour="Curious", special_needs="", description="Adorable and inquisitive kitty.", owner=shelter1)
    petlisting4 = PetListing.objects.create(name="Rocky", category="O", breed="Turtle", age=4, gender="M", size="S", med_history="None", behaviour="Protective", special_needs="", description="A very fast turtle.", owner=shelter1)
    petlisting5 = PetListing.objects.create(name="Bella", category="D", breed="Labrador Retriever", age=5, gender="F", size="L", med_history="None", behaviour="Gentle", special_needs="", description="Sweet-natured and sociable.", owner=shelter1)
    petlisting6 = PetListing.objects.create(name="Oliver", category="C", breed="British Shorthair", age=2, gender="M", size="M", med_history="None", behaviour="Relaxed", special_needs="", description="Easygoing and charming.", owner=shelter1)
    petlisting7 = PetListing.objects.create(name="Daisy", category="D", breed="Beagle", age=3, gender="F", size="M", med_history="None", behaviour="Playful", special_needs="", description="Cheerful and affectionate.", owner=shelter1)
    petlisting8 = PetListing.objects.create(name="Milo", category="C", breed="Ragdoll", age=4, gender="M", size="L", med_history="None", behaviour="Calm", special_needs="", description="Graceful and friendly.", owner=shelter1)
    petlisting9 = PetListing.objects.create(name="Coco", category="D", breed="Poodle", age=1, gender="F", size="S", med_history="None", behaviour="Energetic", special_needs="", description="Lively and adorable.", owner=shelter2)
    petlisting10 = PetListing.objects.create(name="Jasper", category="C", breed="Persian", age=5, gender="M", size="L", med_history="None", behaviour="Independent", special_needs="", description="Elegant and regal.", owner=shelter2)
    petlisting11 = PetListing.objects.create(name="Ruby", category="D", breed="Dachshund", age=2, gender="F", size="S", med_history="None", behaviour="Curious", special_needs="", description="Delightful and playful.", owner=shelter2)
    petlisting12 = PetListing.objects.create(name="Simba", category="C", breed="Maine Coon", age=3, gender="M", size="L", med_history="None", behaviour="Majestic", special_needs="", description="Big-hearted and sociable.", owner=shelter3)
    petlisting13 = PetListing.objects.create(name="Teddy", category="D", breed="Shih Tzu", age=1, gender="M", size="S", med_history="None", behaviour="Affectionate", special_needs="", description="Cute and cuddly companion.", owner=shelter4)
    petlisting14 = PetListing.objects.create(name="Sunny", category="C", breed="Bengal", age=2, gender="F", size="M", med_history="None", behaviour="Adventurous", special_needs="", description="Spirited and graceful.", owner=shelter5)
    petlisting15 = PetListing.objects.create(name="Charlie", category="D", breed="Bulldog", age=4, gender="M", size="L", med_history="None", behaviour="Easygoing", special_needs="", description="Loyal and laid-back.", owner=shelter6)
    petlisting16 = PetListing.objects.create(name="Misty", category="C", breed="Scottish Fold", age=3, gender="F", size="M", med_history="None", behaviour="Gentle", special_needs="", description="Sweet and charming.", owner=shelter7)
    petlisting17 = PetListing.objects.create(name="Brian", category="D", breed="Boxer", age=3, gender="M", size="L", med_history="None", behaviour="Playful", special_needs="", description="Energetic and friendly.", owner=shelter8)
    petlisting18 = PetListing.objects.create(name="Nala", category="C", breed="Sphynx", age=1, gender="F", size="S", med_history="None", behaviour="Affectionate", special_needs="", description="Elegant and loving.", owner=shelter9)
    petlisting19 = PetListing.objects.create(name="Rudy", category="D", breed="Rottweiler", age=4, gender="M", size="L", med_history="None", behaviour="Protective", special_needs="", description="Courageous and devoted.", owner=shelter10)
    petlisting20 = PetListing.objects.create(name="Buddy", category="C", breed="Siamese", age=2, gender="F", size="S", med_history="None", behaviour="Playful", special_needs="", description="Energetic and adorable.", owner=shelter3)
    
    # Applications
    app1 = Application.objects.create(first_name="Bob", last_name="Smith", address="123 Main St", phone="123-456-7890",
                                      email="bobsmith@example.com", contact_pref="E", pet_number=1, has_children=False,
                                      experience="EX", residence_type="C", status="P", seeker=seeker1, shelter=shelter1, petlisting=petlisting1)
    app2 = Application.objects.create(first_name="Bob", last_name="Smith", address="123 Main St", phone="123-456-7890",
                                      email="bobsmith@example.com", contact_pref="E", pet_number=1, has_children=False,
                                      experience="EX", residence_type="C", status="P", seeker=seeker1, shelter=shelter2, petlisting=petlisting2)
    app3 = Application.objects.create(first_name="Bob", last_name="Smith", address="123 Main St", phone="123-456-7890",
                                      email="bobsmith@example.com", contact_pref="E", pet_number=1, has_children=False,
                                      experience="EX", residence_type="C", status="P", seeker=seeker1, shelter=shelter1, petlisting=petlisting3)
    app4 = Application.objects.create(first_name="Bob", last_name="Smith", address="123 Main St", phone="123-456-7890",
                                      email="bobsmith@example.com", contact_pref="E", pet_number=1, has_children=False,
                                      experience="EX", residence_type="C", status="P", seeker=seeker1, shelter=shelter1, petlisting=petlisting4)
    app5 = Application.objects.create(first_name="Bob", last_name="Smith", address="123 Main St", phone="123-456-7890",
                                      email="bobsmith@example.com", contact_pref="E", pet_number=1, has_children=False,
                                      experience="EX", residence_type="C", status="P", seeker=seeker1, shelter=shelter1, petlisting=petlisting5)
    app6 = Application.objects.create(first_name="Bob", last_name="Smith", address="123 Main St", phone="123-456-7890",
                                      email="bobsmith@example.com", contact_pref="E", pet_number=1, has_children=False,
                                      experience="EX", residence_type="C", status="P", seeker=seeker1, shelter=shelter1, petlisting=petlisting6)
    app7 = Application.objects.create(first_name="Kellan", last_name="Rodriguez", address="1234 Main St", phone="987-654-3210",
                                      email="kellanrodriguez@example.com", contact_pref="P", pet_number=2, has_children=True,
                                      experience="IN", residence_type="A", status="P", seeker=seeker2, shelter=shelter1, petlisting=petlisting1)
    app8 = Application.objects.create(first_name="Kellan", last_name="Rodriguez", address="1234 Main St", phone="987-654-3210",
                                      email="kellanrodriguez@example.com", contact_pref="P", pet_number=2, has_children=True,
                                      experience="IN", residence_type="A", status="P", seeker=seeker2, shelter=shelter2, petlisting=petlisting2)
    app9 = Application.objects.create(first_name="Kellan", last_name="Rodriguez", address="1234 Main St", phone="987-654-3210",
                                      email="kellanrodriguez@example.com", contact_pref="P", pet_number=2, has_children=True,
                                      experience="IN", residence_type="A", status="P", seeker=seeker2, shelter=shelter1, petlisting=petlisting3)
    app10 = Application.objects.create(first_name="Elara", last_name="Monroe", address="1234 St. George St", phone="135-792-4680",
                                      email="elaramonroe@example.com", contact_pref="T", pet_number=2, has_children=True,
                                      experience="EX", residence_type="H", status="P", seeker=seeker3, shelter=shelter1, petlisting=petlisting3)
    
    # Comments
    # Both comments and reviews goes here
    comment1 = Comment.objects.create(content="I would love to see Luna in person!", is_author_seeker=True, seeker=seeker1, shelter=shelter1, is_review=False, application=app1)
    comment2 = Comment.objects.create(content="Sure!, what time are you avaliable to visit our shelter?", is_author_seeker=False, seeker=seeker1, shelter=shelter1, is_review=False, application=app1)
    comment3 = Comment.objects.create(content="Are you guys open on weekends?", is_author_seeker=True, seeker=seeker1, shelter=shelter1, is_review=False, application=app1)
    comment4 = Comment.objects.create(content="Hi! May I get an update on my application?", is_author_seeker=True, seeker=seeker1, shelter=shelter2, is_review=False, application=app2)
    review1 = Comment.objects.create(content="Awesome!", is_author_seeker=True, seeker=seeker1, shelter=shelter2, is_review=True, rating=5)
    review2 = Comment.objects.create(content="I would definitely visit again", is_author_seeker=True, seeker=seeker2, shelter=shelter1, is_review=True, rating=5)
    review3 = Comment.objects.create(content="Very long response time to messages", is_author_seeker=True, seeker=seeker1, shelter=shelter1, is_review=True, rating=3)
    review4 = Comment.objects.create(content="We're very sorry for your inconvenience, we will try to improve next time.", is_author_seeker=False, seeker=seeker1, shelter=shelter1, is_review=True)

    blogpost1 = BlogPost.objects.create(title="Paws and Play: Nurturing a Joyful Bond with Your Furry Friend", content="Welcome to the enchanting world of pet companionship, where every paw-step and playful gesture contributes to the heartwarming symphony of a truly special connection. In the hustle and bustle of our daily lives, our four-legged friends bring a sense of joy, companionship, and unconditional love that is truly unparalleled. Here at our shelter, we are dedicated to providing a comprehensive guide to foster a paw-sitively happy and healthy bond with your furry friend.\nAt the core of every vibrant and active pet is a well-balanced diet and proper healthcare. Delve into our rich repository of insights on pet nutrition, exploring tailored recommendations for different breeds and life stages. From deciphering pet food labels to understanding the significance of routine veterinary care, we aim to empower you with the knowledge needed to keep your pet in the best shape possible.\nA harmonious bond with your pet extends beyond the basics of nutrition and healthcare. Discover a myriad of engaging activities and games designed not only to keep your pets physically stimulated but also to strengthen the emotional connection you share. Whether it's embarking on outdoor adventures, experimenting with interactive toys, or diving into training sessions, our blog is a treasure trove of ideas to keep tails wagging and spirits high.\nIn the vast tapestry of pet companionship, each thread weaves a unique and heartening tale. Join us as we share inspiring stories of rescued pets finding their forever homes, illustrating the transformative impact of these extraordinary relationships on both pets and their loving parents. These narratives serve as a reminder of the profound joy that adopting a furry friend can bring into our lives and the immeasurable positive change that comes with giving a home to a pet in need.\nAs you navigate the delightful journey of pet parenting, our blog strives to be your trusted companion. Beyond being a mere resource, it is a community hub where passionate pet lovers come together to celebrate the highs, navigate the challenges, and revel in the fulfillment that comes with having a furry friend by your side. Welcome to a world where every tail wag and contented purr serves as a testament to the enduring melody of unconditional love. Explore, learn, and be inspired on your quest to foster a paw-sitively happy and healthy bond with your cherished companion.", author=shelter1)
    blogpost2 = BlogPost.objects.create(title="Tales and Tidbits: A Pet-centric Journey into Furry Bliss", content="Step into a world where wagging tails, playful antics, and boundless affection shape the narrative of our blog. At our shelter, we invite you to embark on a heartwarming journey through the realms of pet care hacks, heartening tales, and expert advice, all designed to enhance the lives of you and your beloved pets. Whether you're a seasoned pet parent or a newcomer to the world of furry companionship, our blog is a haven where the shared language of love unites us all.\nDiscover the magic in simplicity as we unravel a collection of pet care hacks aimed at making your life as a pet parent more enjoyable and stress-free. From grooming shortcuts that keep your furry friend looking fabulous to clever feeding solutions that cater to their nutritional needs, our blog is your go-to source for creative yet practical tips. Dive into a world where pet care becomes a joyful ritual, allowing you more time to savor the moments of companionship that make your connection with your pet truly special.\nCelebrate the enchanting stories of companionship that define the heart and soul of our pet-centric community. From rescued pets finding their forever homes to the everyday adventures that create lasting memories, our blog is a storytelling sanctuary. These tales resonate with the universal emotions of love, loyalty, and the unique bond shared between pets and their human companions. Join us as we navigate the emotional landscape of pet parenthood, where each story unfolds as a testament to the extraordinary connections forged with our furry friends.\nAs you reach the end of this blog, we extend an invitation to join our community of pet enthusiasts. Our shelter is not just a repository of information; it's a shared space where experiences are exchanged, and the joys of pet parenthood are celebrated. Let the tales and tidbits inspire you, the hacks simplify your routine, and the expert advice empower you on your journey as a pet parent. Welcome to a world where every wag, purr, and paw print contributes to the narrative of blissful companionship. Here's to creating more heartwarming chapters together in the tapestry of our furry friends' lives!", author=shelter1)
    blogpost3 = BlogPost.objects.create(title="Paws & Pages: A Journey into Pet Enchantment", content="Welcome to a world where pet parenthood transforms into an enchanting adventure. At our shelter, we invite you to unleash a realm of pet-centric wisdom, where every post is a delightful journey filled with practical tips, heartwarming anecdotes, and a touch of pet magic. Whether you're a dedicated pet parent or considering the joy of furry companionship, our blog is your compass to navigate the intricacies of pet care, share in the joyous tales of pet-human bonds, and discover the enchantment that pets bring into our lives.\nEmbark on a paw-some adventure with each blog post, where practical tips are the compass guiding you through the maze of pet care. Dive into a wealth of knowledge designed to make your journey as a pet parent smoother and more enjoyable. From grooming hacks that make bath time a breeze to nutrition insights that cater to your pet's well-being, our blog is your trusted companion in navigating the day-to-day joys and challenges of life with your furry friends. Each post is crafted to be not just informative but a source of inspiration, making your pet-centric adventure all the more magical.\nAs we conclude this chapter, we extend an invitation to join our community of pet enthusiasts. Our shelter is not just a virtual space; it's a sanctuary where pet magic is celebrated, and the wonders of companionship are explored. May the practical tips enhance your pet parenting skills, the anecdotes warm your heart, and the sprinkle of pet magic make each post a joy to explore. Here's to a continuing journey filled with wagging tails, soft purrs, and the enduring enchantment of the pet-human bond. Embrace the magic of pet parenthood with us, one paw print at a time!", author=shelter1)
    blogpost4 = BlogPost.objects.create(title="Chronicles of Compassion: A Shelter's Heartfelt Journey", content="Step into the heartwarming world of our shelter's blog, a sanctuary of stories that weave together the threads of compassion, resilience, and the everlasting bond between humans and their furry friends. Our blog is more than just a collection of words; it's a tapestry of love, each thread representing the unique tales of animals seeking a second chance.\nJourney with us through the emotional highs and lows as we share the inspiring narratives of successful adoptions, where once-homeless pets find their forever families. Explore the depth of our commitment to animal welfare, as we provide insights into responsible pet care, training tips, and health advice that resonate with both seasoned pet parents and those considering adoption.\nImmerse yourself in the joyful celebrations of reunions and the triumphs of rehabilitation, witnessing firsthand the transformative power of love and care. Beyond the anecdotes, our blog stands as a beacon of hope, offering resources for potential adopters, fostering a community of like-minded animal lovers, and fostering awareness about the significance of adopting and caring for our four-legged companions.\nJoin us on this paw-some odyssey as we navigate the challenges and triumphs of our shelter's mission—to create a world where every animal finds a loving home. With every word, we aim to inspire, educate, and build connections that go beyond the digital realm, echoing the heartbeat of our shelter and the creatures we hold dear. Welcome to the Chronicles of Compassion, where each chapter unfolds as a testament to the enduring bond between humans and the animals that grace our lives.", author=shelter1)
    blogpost5 = BlogPost.objects.create(title="Whiskers Chronicle: Tales of Love and Hope", content="Welcome to the enchanting realm of the \"Paws and Whiskers Chronicle,\" where every page unfolds a symphony of heartwarming narratives, weaving together the extraordinary tales of love, boundless hope, and the melodious rhythm of endless wagging tails. In this sanctuary of storytelling, we invite you to immerse yourself in the magical tapestry of our shelter's vibrant community, a place where the echoes of joy resonate through the pawprints of our cherished companions.\nDiscover the intimate stories of transformation as once-stray paws find solace and warmth in the embrace of caring families. From the spirited antics of playful kittens to the wisdom etched in the eyes of senior dogs, each resident at our shelter contributes to the vibrant mosaic of unconditional love that defines our haven.\nBeyond the enchanting tales of adoption triumphs, our chronicle serves as a beacon of knowledge, offering insights into responsible pet ownership, holistic care, and the art of fostering a harmonious bond between humans and their four-legged friends. Delve into the pages filled with tips and tricks, unveiling the secrets to creating a nurturing environment where pets thrive and families flourish.\nJoin us in celebrating the milestones, big and small, as we navigate the evolving landscape of animal welfare. \"Paws and Whiskers Chronicle\" is more than a collection of stories; it is a testament to the resilience of the human spirit and the enduring magic that unfolds when compassionate hearts unite in the name of furry companions.\nSo, let the chronicle guide you through a world where each wagging tail tells a story, and each purr reverberates with the promise of a brighter tomorrow. Welcome to a literary haven where love knows no bounds, hope springs eternal, and every furry friend is a cherished protagonist in the grand narrative of life's most heartening tales.", author=shelter1)
    blogpost6 = BlogPost.objects.create(title="Whispers of Tails: Navigating the Pet Adoption Odyssey", content="Embark on an extraordinary journey through the pages of our shelter's blog, where each entry is a chapter in the ongoing saga of compassion, companionship, and the quest for loving homes. \"Whispers of Tails\" is not just a blog; it's an intimate exploration of the countless stories that unfold within the walls of our shelter, tales of resilience, second chances, and the profound connections that bind us to our furry friends.\nDive into the riveting narratives that highlight the diverse personalities of our four-legged residents, from spirited dogs with tails that wag like exclamation marks to the graceful mystery of enigmatic cats. Discover the heartening chronicles of our adoption success stories, where the convergence of kindred spirits brings joy not only to the animals but also to their new human companions.\nBeyond the anecdotes, our blog is a wellspring of knowledge, offering readers a treasure trove of pet care wisdom, training insights, and expert advice. Uncover the secrets to building a strong and lasting bond with your pets, and learn how simple acts of kindness can transform the lives of animals in need.\nAs you navigate through the pages of \"Whispers of Tails,\" join us in celebrating the wins, big and small, and in advocating for the welfare of all creatures. This blog is a testament to the dedication of our shelter family, the tireless volunteers, and the steadfast supporters who collectively shape a narrative of hope and compassion.\nSo, let the pages turn, and allow the whispers of tails to guide you through the labyrinth of emotions, challenges, and the unwavering love that defines our shared journey in the world of pet adoption. Welcome to a haven where every story is a testament to the magic that unfolds when hearts and paws come together.", author=shelter1)
    
    # Notifications should be created automatically when comments, petlistings, and applications are created
    
    # If you want to create initial_data.json, uncomment the following lines as well as comment out "python3 petpal/script.py" in startup.sh and run "python3 petpal/script.py" in bash
    # data = serialize('json', [seeker1, seeker2, seeker3, shelter1, shelter2, shelter3, petlisting1, petlisting2, petlisting3, petlisting4, app1, app2, comment1, comment2, comment3])
    # with open('initial_data.json', 'w') as f:
    #     f.write(data)
        
if __name__ == '__main__':
    create_initial_data_json()